### PR TITLE
Update CCShake.cpp

### PR DESCRIPTION
**Pull request by frranck**
updated for cocos2d-x 3.x

### CODE REVIEW

**Comment by elnormous** [comment]
Thank you for the pull request. Please change ccp to Point as ccp is deprecated and remove spaces around the parameter in setPosition.

**Comment by elnormous** [comment]
Ok, I made the fixes myself. Thank you for your help!

**Comment by frranck** [comment]
Dude you're suppose to accept merges, that's the way you give credit.. but no worries...

**Comment by elnormous** [comment]
Sorry for that.
PS. I moved this code to other repository: https://github.com/elvman/cocos2d-x-ext

**Pull request closed without merging**
